In [1]:
import numpy as np

**Contenido creado por:**

*Isabel Maniega*

****

# Ejercicio 1

**Dado: "np.arange(2,10)"** 

sigue los siguientes pasos:

**2.1)**

Escribe esa instrucción y asígnaselo a la variable "a"

In [2]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

**2.2)** 

¿Es equivalente a "np.arange(2,10,1)"?

In [3]:
def comparar_arrays(a,b):
    for i in range(len(a)):
        if a[i] != b[i]:
            print(f"{a[i]} y {b[i]} son diferentes")
            return False
    return True



if len(a) == len(np.arange(2,10,1)):
    if comparar_arrays(a,np.arange(2,10,1)):
        print("Son iguales")
    else:
        print("No tiene los mismos valores")
else:
    print("No tienen el mismo tamaño")
    

Son iguales


In [4]:
a = np.arange(2,10)
np.array_equal(a,np.arange(2,10,1))

True

**2.3)** 

se pide quedarse con aquellos **números menores de 5.** 

hazlo con numpy si puedes para la variable "a"

In [5]:
a = np.arange(2,10)
pos_del = []
for i in range(len(a)):
    if a[i] >= 5:
        pos_del.append(i)

np.delete(a,pos_del)        

array([2, 3, 4])

**2.4)** 

hazlo pasando esa información (de "a") a una lista

In [6]:
# pasando a lista..
a = np.arange(2,10)
b = []
for i in range(len(a)):
    if a[i] < 5:
        b.append(a[i])
b

[2, 3, 4]

**2.5)** 

en base a los resultados.. 

¿Es posible recorrer 1 a 1 un array de numpy? 

In [7]:
# responde..
# Sí

**2.6)** 

Haz el mismo proceso programando una sola línea (toma "a" como referencia)

In [8]:
# en una sola línea..
b = np.array([i for i in a if i<5])
b

array([2, 3, 4])

****

# Ejercicio 2

Para estos valores (v de valores por abreviar):

v1 = 4

v2 = 5

v3 = 7

v4 = 8

El objetivo será calcular la media de estos valores

Para ello sigue los siguientes pasos:

**3.1)**

imprime los valores de esas variables v1,v2,v3,v4

In [9]:
# valores..
v1 = 4
v2 = 5
v3 = 7
v4 = 8

print(f"Los valores de las variables són: {v1}, {v2}, {v3} y {v4}")

Los valores de las variables són: 4, 5, 7 y 8


**3.2)**

Descomenta las 2 líneas siguientes para aprender.. 

que es posible asignar varios valores en la misma línea

Y la asignación de valores a variables se hace de forma consecutiva.

In [10]:
 v1,v2,v3,v4 = 4, 5, 7, 8
 v1,v2,v3,v4

(4, 5, 7, 8)

In [11]:
# otro ejemplo: (descomenta las 2 siguientes líneas de código)

x,y=2,3
x,y

(2, 3)

**3.3)** 

Descomenta la línea siguiente para aprender una posible forma de calcular la media.

Usamos nuevamente numpy..

In [12]:
media_numpy = np.mean([v1,v2,v3,v4])
media_numpy

6.0

**3.4)**

Calcula la media sin usar numpy

Si el resultado no sale bien, razona cómo debería hacerse..

In [13]:
# media sin numpy..
media = (v1 + v2 +v3 + v4)/4
media

6.0

****

# Ejercicio 3

**Factorial de un número**

**Nota:**
    
El **Factorial de 5**, por ejemplo:
    
**5! = 5 * 4 * 3 * 2 * 1 = 120**

y el de 3:

3! = 3 * 2 * 1 = 6

y así para todos..

**PASOS A SEGUIR Y COSAS A TENER EN CUENTA** 

Pide por teclado el número del cual quieres calcular el factorial.

Para que no sea muy grande te recomendamos:

3,4 o 5 (para hacer las pruebas)

si ya no lo recuerdas o nunca lo viste, no te preocupes..

3! es: 3 * 2 * 1 = 6

4! es: 4 * 3 * 2 * 1 = 24

5! es: 5 * 4 * 3 * 2 * 1 = 120

(esto es lo que se pide, en esencia)

In [14]:
def factorial_r(x):
    if x < 2:
        return 1
    else:
        return(x*factorial_r(x-1))


In [15]:
def factorial_b(x):
    res = 1
    while x > 1:
        res *= x
        x -= 1
    return res

In [16]:
x = int(input("Introduce número para obtener el factorial: "))
print(f"{x}! = {factorial_r(x)}")

Introduce número para obtener el factorial: 5
5! = 120


## Ejercicio 4

In [39]:
from time import sleep
from IPython.display import clear_output

horas = 0
minutos = 0
segundos = 0
cero_segundos = "0"
cero_minutos = "0"


while horas<2:
    clear_output(wait=True)
    print(f"0{horas}:{cero_minutos}{minutos}:{cero_segundos}{segundos}")
    sleep(0.000001)
    segundos += 1
    
    
    if segundos < 10:
        cero_segundos = "0"
    else:
        cero_segundos =""
        
    if segundos > 59:
        minutos += 1
        segundos = 0
        if minutos < 10:
             cero_minutos = "0"
        else:
            cero_minutos = ""
        if minutos > 59:
            horas += 1
            minutos = 0


01:59:59


****

**Contenido creado por:**

*Isabel Maniega*